library(editrules)
library(dplyr)
setwd("C:\\Users\\anujk\\Documents\\RStudio_p")
data = read.csv("people.csv", header = TRUE, sep = ",")
E = editfile("C:/Users/anujk/Documents/RStudio_p/p_constrants.txt")
modfy <- violatedEdits(E,data)
summary(modfy)
print(data)
print(E)
print(modfy)
print(d)
plot(E)
